### ISSUE TITLE
@cosmos-kit/keplr requires an unpublished @cosmos-kit/core@0.26.2

### ISSUE THREAD

**Issue by grikomsn** [cosmology-tech/cosmos-kit#105]
![CleanShot 2022-12-02 at 06 54 52@2x](https://user-images.githubusercontent.com/8220954/205183723-988857cd-12de-46e9-9d12-70de2f779b19.png)

https://www.npmjs.com/package/@cosmos-kit/core?activeTab=versions

**Comment by grikomsn** [comment]
Seems that `@cosmos-kit/leap` also requires an unpublished package.

![CleanShot 2022-12-02 at 06 57 15@2x](https://user-images.githubusercontent.com/8220954/205184080-31e1a38c-11f3-4a3d-bf86-bcda682e4dd1.png)

**Comment by pyramation** [comment]
thanks for reporting! must have had an internet issue w/o a warning, not sure how this happened :/ 

```
Successfully published:
 - @cosmos-kit/core@0.27.0
 - @cosmos-kit/cosmostation@0.14.0
 - @cosmos-kit/keplr@0.32.0
 - @cosmos-kit/leap@0.13.0
 - @cosmos-kit/react@0.27.0
 - @cosmos-kit/trust@0.13.0
 - @cosmos-kit/vectis@0.14.0
 ```
