### ISSUE TITLE
Chakra theme on default modals breaks existing chakra theme

### ISSUE THREAD

**Issue by grikomsn** [cosmology-tech/cosmos-kit#106]
Existing apps that uses Chakra UI will encounter an issue where the base theme will be overridden with cosmos-kit's default modal because it wraps its own ChakraProvider.

Having the option to disable provider wrapping or provide an escape hatch to pass custom themes would be better.

https://github.com/cosmology-tech/cosmos-kit/blob/8eff22dcdc01fae2eacae57d26952892a50232d3/packages/react/src/modal/get-modal.tsx#L48-L60

**Comment by pyramation** [comment]
totally agree! and thanks for the detailed example

we're actually working on a fix for this in the current sprint! stay tuned, would love your feedback :)

**Comment by liujun93** [comment]
@grikomsn Thanks. This bug has been fixed. Please upgrade to the latest cosmos-kit. Have fun!

```
 - @cosmos-kit/core@0.27.1
 - @cosmos-kit/cosmostation@0.14.1
 - @cosmos-kit/keplr@0.32.1
 - @cosmos-kit/leap@0.13.1
 - @cosmos-kit/react@0.27.1
 - @cosmos-kit/trust@0.13.1
 - @cosmos-kit/vectis@0.14.1
```

view code:

https://github.com/cosmology-tech/cosmos-kit/blob/ab4461dd46ebeb91ccb21b1a9a17bf5b2148c4cd/packages/react/src/modal/get-modal.tsx#L61-L77
