### ISSUE TITLE
Global package versioning

### ISSUE THREAD

**Issue by 0xArbi** [cosmology-tech/cosmos-kit#115]
It'd be awesome if all the packages in this monorepo were versioned and published at the same time, so users can just consume one version (ie. `0.27.5`) instead of having to manually check each dependency to ensure we're on the latest.

See the [cosmos-kit example project](https://github.com/cosmology-tech/cosmos-kit/blob/main/packages/example/package.json#L19) for how projects will look with different versions of everything. A little messy

**Comment by pyramation** [comment]
we could update it once to make them the same today, but as we use [`lerna publish`](https://github.com/lerna/lerna/tree/main/commands/publish), they'd eventually get out of sync unless we manually updated packages.

**Comment by pyramation** [comment]
The reason we use lerna is that it makes things very simple to manage a mono repo. 

I recommend using `yarn upgrade-interactive --latest` if you want to upgrade, have you ever used that one?

**Comment by 0xArbi** [comment]
Just tried it! Yes it's quite a nice command.

The tradeoff is between developers having to release every package for every change, and users having to manage versions independently. I prefer the latter but appreciate that this library is still quite young, so there's a lot of overhead for you guys doing this at the moment. 

Maybe a thing to revisit when it reaches 1.0!
