### ISSUE TITLE
brave browser loaded w extensions, ad blockers, produces errors

### ISSUE THREAD

**Issue by pyramation** [cosmology-tech/cosmos-kit#120]
## environment

brave browser (loaded with extensions, ad blockers, etc)

Seems that somehow the detection for whether or not we're mobile was triggering, even though the user agent was still chrome!

## issue

errors happen with connecting 

![Screen Shot 2022-12-16 at 2 53 21 PM](https://user-images.githubusercontent.com/545047/208202657-a726f9dd-42de-4a1c-92e3-4fe4ca2f3382.png)

![Screen Shot 2022-12-16 at 3 01 18 PM](https://user-images.githubusercontent.com/545047/208202660-e49669a2-3716-45b9-92ee-90976d83f4e5.png)

## steps to reproduce

1. create template

```
create-cosmos-app --name cnfts-frontend --example --template cosmwasm
```

2. attempt to connect wallet

However, it looks that the browser was somehow choosing the keplr mobile — so this is maybe why the offlineSigner was undefined... but why was it 1. using mobile and 2. trying get get a signer before actually connecting?

## idea to debug

Perhaps we should test using keplr mobile as the chosen wallet inside of chrome and see what happens

## important note

as soon as developer removed all extensions by creating fresh profile only with keplr extension, everything worked fine

**Comment by liujun93** [comment]
@pyramation  Can't reproduce it on Brave and Chrome
