### ISSUE TITLE
allow usage of `HttpEndpoint` for urls

### ISSUE THREAD

**Issue by pyramation** [cosmology-tech/cosmos-kit#122]
Telescope and CosmJS support `HttpEndpoint` which allows users to pass headers into requests, cosmos-kit should support this. Perhaps we just need to make a modified version of `chain-registry/types` to allow for this

https://github.com/osmosis-labs/osmojs/blob/843b315fa0bc304eebc7664c152c18cc1871792c/packages/osmojs/src/codegen/osmosis/rpc.query.ts#L6

```
export interface HttpEndpoint {
  /**
   * The URL of the HTTP endpoint.
   *
   * For POST APIs like Tendermint RPC in CosmJS,
   * this is without the method specific paths (e.g. https://cosmoshub-4--rpc--full.datahub.figment.io/)
   */
  readonly url: string;
  /**
   * HTTP headers that are sent with every request, such as authorization information.
   */
  readonly headers: Record<string, string>;
}
```

**Comment by liujun93** [comment]
Done and published
