### ISSUE TITLE
Split keplr mobile / extension to separate deps

### ISSUE THREAD

**Issue by TrevorJTClarke** [cosmology-tech/cosmos-kit#125]
I know this might sound controversial, but I actually want to be able to import keplr mobile/extension separately because wallet connect brings in a ton of stuff that has awful commonjs modules that need pre-transpiling for non-react/next projects. I also don't necessarily want a WS ping/ack added for simply adding a keplr query provider.

See this line specifically:  https://github.com/cosmology-tech/cosmos-kit/blob/main/packages/keplr/src/keplr.ts#L9

SO!
I am proposing that they get split into 2 packages, so it can be independently added.
I realize this is a breaking change for some projects, but I believe for future work, this pattern of context splitting for any provider (cosmostation, leap, you name it) is necessary for more granular inclusion.

Thoughts?
If there's a way to disable keplr wallet already - would love to know :)

**Comment by pyramation** [comment]
I think it's a fair point! I suppose in this world, we'd have one wallet per package?

**Comment by TrevorJTClarke** [comment]
Yep! If that is okay with you - I can do a split to make this work, however it will likely need to be like the following for backward compat:

```
# Inside packages:
/keplr (just exports the combined set of mobile + ext)
/keplr-mobile
/keplr-extension
/cosmostation
/cosmostation-mobile
/cosmostation-extension
```

if you're good with that @pyramation then i can contribute that

**Comment by sascha1337** [comment]
more abstraction for vue4 n vite would be great as h3ll frens, is this
possible already ?

**Comment by pyramation** [comment]
> Yep! If that is okay with you - I can do a split to make this work, however it will likely need to be like the following for backward compat:
> 
> ```
> # Inside packages:
> /keplr (just exports the combined set of mobile + ext)
> /keplr-mobile
> /keplr-extension
> /cosmostation
> /cosmostation-mobile
> /cosmostation-extension
> ```
> 
> if you're good with that @pyramation then i can contribute that

I think that would work! Thanks! Before you go and do the work, we may want to merge a branch first as we may have quite a few changes...

We'd have to update the docs too, let's run this by @liujun93 so we can get a checklist of all things to consider, we're going to meet tonight and can go over this asap!

**Comment by TrevorJTClarke** [comment]
> We'd have to update the docs too

sounds great!
Hit me with the list, i can do a first pass tonight or tmoro night.
Cheers

**Comment by pyramation** [comment]
thumbs up! go ahead and we are excited about your PR!
we can help update docs w @liujun93

**Comment by TrevorJTClarke** [comment]
See PR #128 - I've been using an internal project to test the connections and can prove its working.

Will finalize this for all wallets and do some documentation, then it will be ready.

NOTE: I was unable to have 100% success with Vectis & Trust wallets, I assume these are still in flux. Vectis appears to not conform to all the hooks.

**Comment by pyramation** [comment]
closed with https://github.com/cosmology-tech/cosmos-kit/pull/129
