### ISSUE TITLE
use `chain-registry` for chain info

### ISSUE THREAD

**Issue by pyramation** [cosmology-tech/cosmos-kit#13]
let's look into using chain-registry to make this type of thing

https://github.com/cosmology-tech/cosmos-wallet/blob/2e66939d241f06516673598f035dbaa00ed6e828/packages/core/src/chainInfo.ts

oh, actually... @NoahSaso I just got an idea if we should parse JSON and generate objects, or if I should look into using ASTs + codegen haha

https://github.com/cosmology-tech/chain-registry and https://www.npmjs.com/package/chain-registry

**Comment by pyramation** [comment]
some examples of how easy it is, here is example where `chain_name=juno`:

```
import { chains, assets } from "chain-registry";
const chain = chains.find((chain) => chain.chain_name === "juno");
const chainAssets = assets.find((asset) => asset.chain_name === "juno");
const chainAsset = chainAssets.assets[0];
const assetImage = chainAsset.logo_URIs.png;
```

and here is a codesandbox https://codesandbox.io/s/funny-mirzakhani-hxtn54

**Comment by TrevorJTClarke** [comment]
Was going to suggest, but happy to see this is already an issue - chain registry is awesome!
