### ISSUE TITLE
Broken links on website

### ISSUE THREAD

**Issue by cryptoclans** [cosmology-tech/cosmos-kit#138]
on this page:
https://docs.cosmoskit.com/use-chain

at the bottom, the examples section links are broken:

🚀 [fetch address](https://github.com/cosmology-tech/cosmos-kit/blob/main/packages/example/pages/chains/index.tsx)
🚀 [fetch balance & send tokens](https://github.com/cosmology-tech/cosmos-kit/blob/main/packages/example/pages/chains/tx.tsx)
🚀 [vote](https://github.com/cosmology-tech/cosmos-kit/blob/main/packages/example/pages/chains/gov.tsx)

**Comment by liujun93** [comment]
@cryptoclans Solved! Thank you!
