### ISSUE TITLE
Expose getKey

### ISSUE THREAD

**Issue by srph** [cosmology-tech/cosmos-kit#145]
I'm very new to cosmos-kit - nice work here! Excited to see it grow.

Would it be possible that either useChain or useManager exposes getKey?

At the moment, I have to jump through a few hoops to do this: https://github.com/srph/issue-evmos-ibc/blob/master/pages/index.tsx#L98

My use-case is that I have to use/make own signer as I need a different pubkey encoder (as opposed to using SigningStargateClient which hard-codes the pubkey encoder).

**Comment by pyramation** [comment]
pardon the delay! we can likely do it, will add this asap!

also curious about making a way to create another pubkey encoder, does that sound interesting and something we should also consider?

**Comment by liujun93** [comment]
@srph I can expose wallet client in `useChain`, `getKey` is renamed as `getAccount` in wallet client. It'll be updated in next version

https://github.com/cosmology-tech/cosmos-kit/blob/d5811b39454a387cb15dacb0230da1c085b96b43/packages/core/src/types/wallet.ts#L121-L164

**Comment by srph** [comment]
Thanks <3
