### ISSUE TITLE
Add verbose parameter to wallet provider

### ISSUE THREAD

**Issue by professionallyatortoise** [cosmology-tech/cosmos-kit#147]
When debugging a web app, cosmos-kit emits many console logs making it difficult to sift through what I am debugging and what's unrelated.

![Screen Shot 2023-01-27 at 10 47 01](https://user-images.githubusercontent.com/95767439/215144714-78a23774-9f55-4682-9b8a-5ccff6efa6b8.png)

I suggest we add a verbose parameter to the wallet provider which we can toggle as needed, and set to false by default

**Comment by liujun93** [comment]
Good idea! will be updated in next version, thank you!
