### ISSUE TITLE
"code":-32603,"message":"Internal error","data":"transaction indexing is disabled"

### ISSUE THREAD

**Issue by kombos** [cosmology-tech/cosmos-kit#151]
I'm trying to execute transactions using cosmos-kit and telescope generated modules for cosmos and gravitybridge and sometimes after executing txns, i get this error: 
"code":-32603,"message":"Internal error","data":"transaction indexing is disabled"

This error is returned even though the transaction went through. This doesnt occus everytime and is very intermittent.

**Comment by pyramation** [comment]
this is an issue with the nodes and public RPC endpoints. We cannot fix this directly, but we could look into an exception handler.
