### ISSUE TITLE
Issues with XDEFI wallet integration - keplr dependant & disconnect() error

### ISSUE THREAD

**Issue by kombos** [cosmology-tech/cosmos-kit#153]
facing the following issues in  @cosmos-kit/xdefi-extension@0.13.20

1. if we remove keplr extension, then xdefi connected status shows 'not exist'.. also when we switch accounts in keplr, it switches in the app, even though the app is connected to xdefi extension. 

2. on calling disconnect(), it throws an error shown below (also screenshot): 
Uncaught (in promise) TypeError: this.client.disconnect is not a function
    at XDEFIClient.disconnect (client.js:16:23)
    at ChainXDEFIExtension.eval [as disconnect] (wallet.js:30:38)
    at async eval (repository.js:50:9
    
    
<img width="955" alt="image" src="https://user-images.githubusercontent.com/18464450/219025733-5de76d06-a3a5-49b8-b4b0-c51f041a6c9c.png">

**Comment by liujun93** [comment]
@kombos We don't suggest using XDEFI yet because it doesn't support cosmos chains yet

https://documents.xdefi.io/
