### ISSUE TITLE
Localstorage _restoreAccounts is causing exponential cache growth

### ISSUE THREAD

**Issue by TrevorJTClarke** [cosmology-tech/cosmos-kit#155]
See the following 2 spots:
1. https://github.com/cosmology-tech/cosmos-kit/blob/main/packages/core/src/manager.ts#L253
2. https://github.com/cosmology-tech/cosmos-kit/blob/main/packages/core/src/bases/chain-wallet.ts#L134

Basically - only 1 of these places should be getting the whole list OR there needs to be an object instead of array. This logic currently creates more and more records everytime "onMounted" gets called.

**Comment by TrevorJTClarke** [comment]
Side effect - takes the wallet longer and longer to load

**Comment by pyramation** [comment]
cc @liujun93

**Comment by grikomsn** [comment]
Temporary hotfix to dedupe cache:

```tsx
import type { SimpleAccount } from "@cosmos-kit/core";

const Hotfix = () => {
  useEffect(() => {
    const key = "cosmos-kit@1:core//accounts";
    const accounts = JSON.parse(localStorage.getItem(key) || "[]") as SimpleAccount[];
    if (!accounts.length) return;
    const map = new Map<string, SimpleAccount>();
    for (const account of accounts) {
      map.set(account.address, account);
    }
    localStorage.setItem(key, JSON.stringify(Array.from(map.values())));
  }, []);

  return null;
};

return (
  <ChainProvider>
    {children}
    <Hotfix />
  </ChainProvider>
);
```

**Comment by liujun93** [comment]
@TrevorJTClarke @grikomsn This problem shall be solved in the latest version. Thanks.

Btw, we still use array instead map in case we allow multiple addresses/accounts for the same chainId in the future. But for now we simply filter out the same chainId before add new account data in.

https://github.com/cosmology-tech/cosmos-kit/blob/e2a6a4c2a374168e3b0d501ed5b5948882ce2168/packages/core/src/bases/chain-wallet.ts#L137-L139

**Comment by TrevorJTClarke** [comment]
cool beans - thanks @liujun93!!
