### ISSUE TITLE
Feature: Lazy RPCs - 

### ISSUE THREAD

**Issue by TrevorJTClarke** [cosmology-tech/cosmos-kit#156]
Background: On each page load, "Testing accessibility ..." happens for ALL RPC providers, which happens to be a lot of providers if using more than 1 network. This adds seconds to the blocking page load. (each network has added ~1.2seconds blocking page load -- EX: Juno, stargaze, osmosis ~3.4 seconds load time of just RPC ping check cycle)

Idea:
Only "Testing accessibility ..." of a set of RPC providers for given network on first request of network. Then as requests come in, just lazily eval which network hasn't had this check yet.

**Comment by sascha1337** [comment]
might sound something for a web worker ...?

**Comment by TrevorJTClarke** [comment]
> might sound something for a web worker ...?

Would that introduce weird latency or complexity for contexts? Sounds neat, but i still think its not necessary to pre-empt connections if they arent used yet

**Comment by liujun93** [comment]
@TrevorJTClarke Can you check your code and make sure you didn't call either `getRpcEndpoint`, `getRestEndpoint`, `getStargateClient`, `getCosmWasmClient`, `getSigningClient`, `getSigningStargateClient`, `getSigningCosmWasmClient`, `getNameService`, `sign`, `broadcast`, or `signAndBroadcast` during page loading period? Testing accessibility only happens when you need an accessible endpoint. It won't be fired if you don't need it. It is a lazy load.

**Comment by TrevorJTClarke** [comment]
hey @liujun93 - im def using `getRpcEndpoint`, which basically happens during app start to load from the previous cache, since we have an app with multiple data sources across juno, osmosis, stargaze (soon more), i need to do a query across each for changes as soon as local cache has loaded. It is totally working, but when RPC providers get overloaded (osmosis is worst usually), having these test accessibility just to get the provider URL isnt exactly ideal. Osmosis bottleneck appears to be wasm queries, main SDK queries are super fast.
I get the nice UX of checking before returning, just wonder if I need to manager the "lazy"ness on my end, or if theres a way i can poke the method differently? 
Any ideas?

**Comment by liujun93** [comment]
@TrevorJTClarke I added a param `isLazy` in `getRpcEndpoint` and `getRestEndpoint` to control the "lazy"ness in the latest version. Is this meet your need?

https://docs.cosmoskit.com/use-chain#methods
