### ISSUE TITLE
Feature: Wallet Change hook

### ISSUE THREAD

**Issue by TrevorJTClarke** [cosmology-tech/cosmos-kit#157]
See documentation for Keplr: https://docs.keplr.app/api/#change-key-store-event
See documentation for Cosmostation: https://docs.cosmostation.io/docs/Developer%20Guide/Cosmostation%20Extension/Cosmos%20chains/event#vanilla-code

Would be great to have a way for me to register action hook or similar, that gets sourced by the wallet.

**Comment by liujun93** [comment]
Hi, @TrevorJTClarke We've add event feature. 

docs here. https://docs.cosmoskit.com/use-manager#events

usage example here. https://github.com/cosmology-tech/cosmos-kit/blob/main/packages/example/pages/event.tsx

The only event so far is `refresh_connection`. Every time registered events `connectEventNamesOnWindow` and `connectEventNamesOnClient` (usually include accounts change event in wallet extension) are triggered, `refresh_connection` would also be triggered.
