### ISSUE TITLE
How to suggest a chain?

### ISSUE THREAD

**Issue by NarutoUjumaki** [cosmology-tech/cosmos-kit#160]
This is not an issue per say. I am just unable to understand where to suggest a chain. I did not find anything from the examples.

**Comment by pyramation** [comment]
do you mean local or testnets?

https://docs.cosmoskit.com/chain-provider#adding-localnet-and-testnets

**Comment by NarutoUjumaki** [comment]
I am trying to suggest a testnet, but I believed local nets would be
suggested the same way.  If not I would need both. Thank you!

**Comment by pyramation** [comment]
they are the same :)

**Comment by NarutoUjumaki** [comment]
Yes there was another issue on my end. i failed to understand that.

**Comment by RicFer01** [comment]
Hi, sorry I know it's closed, but I'm trying to do the same, I'm adding a testnet, I did all the steps [docs.cosmoskit.com/chain-provider#adding-localnet-and-testnets](https://docs.cosmoskit.com/chain-provider#adding-localnet-and-testnets) but I cannot see my testnet in keplr under non native chains and so I cannot connect, it's triggering the error, any suggestion, please?
