### ISSUE TITLE
Missing useChain export

### ISSUE THREAD

**Issue by 0xArbi** [cosmology-tech/cosmos-kit#161]
The latest version of `@cosmos-kit/react` doesn't export the `useChain` hook anymore, breaking my build.

I suspect the reason is because its been moved to `react-lite`, and `react` is supposed to export everything from `react-lite`. But the export statement `export * from '@cosmos-kit/react-lite/src/hooks';`, looks wrong. I believe it should be exporting the built directory.

**Comment by pyramation** [comment]
where is the `export * from '@cosmos-kit/react-lite/src/hooks';` statement?

**Comment by pyramation** [comment]
yea we should remove this https://github.com/cosmology-tech/cosmos-kit/blob/9e064d9d837ea4480b25ec6c74097ab6a7562366/packages/react/types/index.d.ts#L1 

cc @liujun93

**Comment by liujun93** [comment]
@0xArbi Fixed in the latest version. Thanks
