### ISSUE TITLE
How can I connect multiple chains at once?

### ISSUE THREAD

**Issue by DavideSegullo** [cosmology-tech/cosmos-kit#164]
I am trying to integrate cosmos-kit within a new project, previously I was using a chain-id array to enable all chains at once, using [keplr enable method](https://docs.keplr.app/api/#enable-connection), which accepts an array of chain-id:

<img width="361" alt="image" src="https://user-images.githubusercontent.com/17269969/226293282-9380e816-b247-42c6-bbd8-21476d476889.png">

Is it possible to do the same thing using cosmos-kit?
In your examples I can only see that an enable modal is opened for each chain you want to connect.

**Comment by liujun93** [comment]
@DavideSegullo [`useWalletClient`](https://docs.cosmoskit.com/hooks/use-wallet-client) exposes wallet client, and the client object provides method `enable`, which supports chain array as parameter.

https://github.com/cosmology-tech/cosmos-kit/blob/55eedfab503a2abdb31d5fd4d047b63cfead3b36/packages/core/src/types/wallet.ts#L137

**Comment by DavideSegullo** [comment]
Hello @liujun93 , I had a look, but this seems to work only if you have already connected a wallet (e.g. Keplr), so if a walletRepo already exists.

How can I get this to work the moment I open the modal?

**Comment by liujun93** [comment]
@DavideSegullo this method doesn't require a CONNECTED wallet, but need you to provide `walletName` as param. if it's not provided, it will use the currently CONNECTED wallet. 

A walletRepo stores all chainWallets for *a particular chain* (you can even use `chainName` as the walletRepo identifier). So if a walletRepo already exists, the chain is also decided. The default modal provided by CosmosKit is about a walletRepo, and displays wallet status for a particular chain. So we can't get `enable multiple chains` work with this modal schema. 

Maybe in the future when we design an advanced modal structure that displays multiple chains without making the modal look overloaded, we can integrate this method in the modal. :)

**Comment by liujun93** [comment]
@DavideSegullo If you want to build an ibc dapp, you can use our ibc template

`cca --name myibctransferapp --example --template ibc-transfer`

also lots of other templates available here.

https://github.com/cosmology-tech/create-cosmos-app

**Comment by pyramation** [comment]
@liujun93 — isn't there a way to do this programmatically and not in the modal? I think with client, I think it's `enableChains` or `enableChainIds`?

**Comment by dillu24** [comment]
> @liujun93 — isn't there a way to do this programmatically and not in the modal? I think with client, I think it's `enableChains` or `enableChainIds`?

Interested to see if this possible. Our team has been finding issues when using the hooks in some instances.

**Comment by twhy** [comment]
@dillu24 
The best you can do for now
```javascript
export default function Home() {
  const { connect } = useChain('cosmoshub');
  const { client } = useWalletClient();

  useEffect(() => {
    if (client) {
      client.enable?.(['cosmoshub-4', 'osmosis-1', 'juno-1'])
      client.getAccount?.('juno-4').then((account) => console.log(account))
      client.getSimpleAccount?.('juno-4').then((account) => console.log(account))
      client.getAccount?.('osmosis-1').then((account) => console.log(account))
      client.getSimpleAccount?.('osmosis-1').then((account) => console.log(account))
      client.getAccount?.('cosmoshub-4').then((account) => console.log(account))
      client.getSimpleAccount?.('cosmoshub-4').then((account) => console.log(account))
    }
  })

  return (
    <div style={{ textAlign: 'center', margin: '4rem' }}>
      <Button onClick={connect}>Connect</Button>
    </div>   
  );
}
```
or 
```javascript
const { client } = useWalletClient('keplr-extension');

useEffect(() => {
  if (client) {
    client.enable?.(['cosmoshub-4', 'osmosis-1', 'juno-1'])
  }
})
```

**Comment by twhy** [comment]
Please use `useChains` in lastest version of CosmosKit.
