### ISSUE TITLE
Bug: Session Callback Infinite Loop

### ISSUE THREAD

**Issue by JoseRFelix** [cosmology-tech/cosmos-kit#165]
## Problem 

If there are defined actions for the wallet, the [default callback](https://github.com/cosmology-tech/cosmos-kit/blob/55eedfab503a2abdb31d5fd4d047b63cfead3b36/packages/core/src/manager.ts#L58-L61) creates an infinite loop when the session duration has expired.

 It is likely that the cause of this issue is the following line https://github.com/cosmology-tech/cosmos-kit/blob/55eedfab503a2abdb31d5fd4d047b63cfead3b36/packages/core/src/manager.ts#L59

**Comment by liujun93** [comment]
@JoseRFelix I didn't find infinite loop when the session duration expired in default disconnect actions. But if there are defined actions (overriding default actions) in your code causing infinite loop, I suggest setting your own callback function by providing [`sessionOptions`](https://docs.cosmoskit.com/provider/chain-provider#sessionoptions) in `ChainProvider`
