### ISSUE TITLE
Station Wallet Integration

### ISSUE THREAD

**Issue by JakeHartnell** [cosmology-tech/cosmos-kit#168]
One of the more popular wallets and great UX. We really should have an integration for this.

**Comment by riley-stride** [comment]
This is being worked on by @afsardo @fl-y. It's blocked. Currently blocked by Station, they need to upgrade to the latest feather version.

**Comment by tansawit** [comment]
Been working on it with TFL for a while on this. Only 1-2 issues left before we're good to go.

ref: https://github.com/alleslabs/cosmos-kit/pull/1
