### ISSUE TITLE
get query clients without connecting to wallet

### ISSUE THREAD

**Issue by vinodhum** [cosmology-tech/cosmos-kit#170]
Hi, 
is it possible to get getCosmWasmClient & getStargateClient without user connecting to wallet.
currently it returns only if user is connected to wallet.

**Comment by pyramation** [comment]
Great point and I believe this is possible? cc @liujun93 

signing clients will need to have connection, but query clients shouldn't need to. Totally agree.

**Comment by liujun93** [comment]
@vinodhum We don't require connected status if getCosmWasmClient & getStargateClient.

try this

```tsx
import { useChainWallet, useChain } from "@cosmos-kit/react";
import { useEffect } from "react";

export default function TestPage() {
  const { getStargateClient } = useChain("cosmoshub");
  //   const { getStargateClient } = useChainWallet("cosmoshub", "keplr-extension");

  useEffect(() => {
    getStargateClient().then((client) => {
      console.log("%ctest.tsx line:9 client", "color: #007acc;", client);
    });
  }, []);

  return <div></div>;
}
```

**Comment by vinodhum** [comment]
Thank you @liujun93, for some reason when I tried it didn’t work but your code works, Thank you.
