### ISSUE TITLE
add a wallet connect wallet in addition to wallet connect enabled wallets

### ISSUE THREAD

**Issue by pyramation** [cosmology-tech/cosmos-kit#172]
let's add another wallet item in our list. Since wallet connect v2 generates the same QR code for any wallet, would be nice to add a wallet connect option.

Additionally, we should consider making wallet connect the 2nd default option next to keplr.

**Comment by liujun93** [comment]
I tried before but we cannot avoid  making wcv2 option for each wallet because they are required on mobile. we cannot simply provide a wcv2 option on mobile because each wallet has different appUrl and deeplink format. In this case a wallet connect option only works on desktop. Do we still need it?

**Comment by pyramation** [comment]
cc @sunnya97
