### ISSUE TITLE
when adding chains from cosmos/chain-registry, cosmos.directory endpoints overrides functional chain-registry endpoints

### ISSUE THREAD

**Issue by jcstein** [cosmology-tech/cosmos-kit#173]
On version [`1.10.0` of chain registry](https://github.com/jcstein/rollkit-frontend/blob/d8835267d6dc0dc6c92ca33baf975ad2bb0e3d26/package.json#L24) on this [repository](https://github.com/jcstein/rollkit-frontend) and [live site's multi-chain page](https://rollkit-frontend.vercel.app/multi-chain), I am adding "Celestia's Mocha Testnet", which has [endpoints](https://github.com/cosmology-tech/chain-registry/blob/ffcf72b1c19f90354beca294ff5224ff6577f0ea/packages/chain-registry/src/chains.ts#L17290-L17300) in 1.10.0 of chain-registry

However, the endpoints that are suggested when I add the chain are from cosmos.directory. If I add the chain, and modify the endpoints manually in `keplr > settings > endpoints > change RPC/API`, I am able to successfully add the chain

So, I think there is a check happening before the chain is suggested, that is switching from the working endpoint to one on cosmos.directory that doesn't exist. Ideally, the endpoints that are added are the same as [these](https://github.com/cosmos/chain-registry/blob/5bfe70654c0fc2853d491af055aea3ae857f7208/testnets/celestiatestnet3/chain.json#L42-L55)

Here's a [video overview](https://www.loom.com/share/9036dc2013924626a7e70d80f6739a64), if it helps clarify anything 😄

**Comment by pyramation** [comment]
just transferring this to cosmos-kit — is this more likely a create-cosmos-app issue with the particular example?

@liujun93 let me know we can move it back, but I thought it was potentially cosmos-kit

**Comment by liujun93** [comment]
@jcstein It should be from cosmos-kit. By default cosmos-kit pick the fasted endpoint from all endpoints. There is a validation process. You can choose to disable validation by setting `isLazy`.  Here is the doc. https://docs.cosmoskit.com/provider/chain-provider#islazy

In you code I suggest setting like this:

```ts
endpointOptions={{
  isLazy: true,
}}
```

and you need to upgrade cosmos-kit version to the latest because I moved the priority of `cosmos.directory` to the lowest

**Comment by jcstein** [comment]
thank you so much @pyramation and @liujun93. I added `isLazy: true` to `endpointOptions` and also updated version of cosmos-kit. working as expected now after 5dfbaf7eab9737b82606f61ad4ad8297dfa738db 😄
