### ISSUE TITLE
Suggest CW20 Token Capability

### ISSUE THREAD

**Issue by DavideSegullo** [cosmology-tech/cosmos-kit#177]
Hi, is it already possible to suggest a cw20 token to add to a wallet?

For example keplr and cosmostation have this functionality, maybe it could be included in 'WalletClient'?

References:
- [keplr](https://docs.keplr.app/api/secretjs.html#suggest-adding-snip-20-tokens-to-keplr)
- [cosmostation](https://docs.cosmostation.io/integration-extension/cosmos/cw20-token#code-using-cosmostationextension-client)

Thank you!

**Comment by pyramation** [comment]
Great idea! Following the PR

**Comment by DavideSegullo** [comment]
Has been implemented in the PR #179 , I think I can close the issue, thank you!
