### ISSUE TITLE
Leap wallet should support add chain

### ISSUE THREAD

**Issue by cnotethegr8** [cosmology-tech/cosmos-kit#178]
Currently cosmos-kit supports adding custom chains with some of the wallets such as [Keplr](https://github.com/cosmology-tech/cosmos-kit/blob/main/wallets/keplr-extension/src/extension/client.ts#L65-L84) and [Cosmostation](https://github.com/cosmology-tech/cosmos-kit/blob/main/wallets/cosmostation-extension/src/extension/client.ts#L99-L117). The Leap wallet however is missing this functionality.

The [Leap docs](https://docs.leapwallet.io/cosmos/connect-to-leap/suggest-chain) show this feature is supported. Can you add it?

**Comment by pyramation** [comment]
cc @baryon2
