### ISSUE TITLE
addChain does not support stakeCurrency which is required for Sei and Keplr

### ISSUE THREAD

**Issue by lvn-skate-dragon** [cosmology-tech/cosmos-kit#191]
When trying to connect to the Sei testnet (`atlantic-2`) using Keplr, an error is thrown of:
> "stakeCurrency" is required

In the [Keplr Chain Registry](https://github.com/chainapsis/keplr-chain-registry) the param `stakeCurrency` can be found.
However, in the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry) this param can't be found. That includes its case-respective alternative, `stake_currency`.

If the Sei network is added to Keplr by connecting it through an external source, such as their [faucet](https://app.seinetwork.io/faucet), it will connect without an issue. 

In the chain blob Keplr presents for approval you can see the following:
```json
"stakeCurrency": {
  "coinDenom": "SEI",
  "coinMinimalDenom": "usei",
  "coinDecimals": 6
},
```

Now that Sei is included in Keplr, connecting to a cosmos-kit app will work, since we added it with the `stakeCurrency` param.

Please add the ability to include this param.

**Comment by liujun93** [comment]
@lvn-skate-dragon We're using `import { chainRegistryChainToKeplr } from '@chain-registry/keplr';` to convert [Cosmos Chain Registry](https://github.com/cosmos/chain-registry) to [Keplr Chain Registry](https://github.com/chainapsis/keplr-chain-registry). `stakeCurrency` is converted as follows. 

https://github.com/cosmology-tech/chain-registry/blob/51dac38c0a630c1ca49d55de9b4a9c71665a6775/packages/keplr/src/index.ts#L99-L101

So "stakeCurrency" should be obtained if you correctly provide the Sei testnet (atlantic-2)  `chain` and `assetList` info.

Did you add them in `ChainProvider`?

**Comment by lvn-skate-dragon** [comment]
@liujun93 thanks, you pointed me in the right direction. 

It seems like `seitestnet` is mapped to 3 different `AssetList`s instead of just the one relevant for v1.

Since I'm using `seitestnet2` I would expect the `chain_name` to have this key. Look at item 164 in my screenshot.

<img width="939" alt="Screenshot 2023-05-04 at 9 31 55" src="https://user-images.githubusercontent.com/131592148/236127550-2416d08c-2785-430e-bd65-cc1c3fee410d.png">

**Comment by liujun93** [comment]
@lvn-skate-dragon Glad it helps. 

About the 3 items on screenshot, I don't see difference. Maybe you can choose any one? 

As for `chain_name`, feel free to modify it before it's added to `ChainProvider` props (both `chains` and `assetLists`).

**Comment by lvn-skate-dragon** [comment]
@liujun93 sorry if it wasn't clear. The difference with those three objects is the `chain_name`. 
Each of them have the value `seitestnet`, but really they should have the values `seidevnet3`, `seitestnet`, and `seitestnet2`. 

The issue then comes when trying to map them. So if I know my chain is `seitestnet2` and I loop through the `assets` list for a `chain_name` with this value, none will return.

It seems like this issue however is not with you but with [chain-registry](https://github.com/cosmos/chain-registry). If that's correct, then this can be closed.

**Comment by lvn-skate-dragon** [comment]
Opened a [PR](https://github.com/cosmos/chain-registry/pull/2063). This can be closed.
