### ISSUE TITLE
consider adding logo folder for raw github links

### ISSUE THREAD

**Issue by pyramation** [cosmology-tech/cosmos-kit#197]
![photo_2023-05-11 13 21 02](https://github.com/cosmology-tech/cosmos-kit/assets/545047/b3cba955-ad1d-4573-929b-a08d1ae94e6f)

https://github.com/cosmology-tech/cosmos-kit/blob/main/wallets/vectis-extension/src/extension/registry.ts

what if we used a link to our repo here, so we don't end up with dead links?

**Comment by pyramation** [comment]
we would NOT include the logo in the wallet packages, however, in the root directly, a `logos/` folder for the images.

**Comment by vexxvakan** [comment]
Would be much appreciated, great idea. I wanted to create a PR for this in the next few days/weeks but if you get to it thats even better

I recently got around to get the new Vectis logo as well which I just uploaded [here](https://gcdnb.pbrd.co/images/8sK7ySB31hPd.jpg)

**Comment by twhy** [comment]
My plan on this:
1. Add a `public` folder at project root in `main` branch directly and use it store static files.
2. Collect the wallet logos and store them at `public/images/logos/wallets/wallet-name.ext`
    - `/public/images/logos/wallets/coin98-extension.png`
    - `/public/images/logos/wallets/cosmostation-extension.png`
    - ...
3. Update `logo` field in `registry.ts` in every wallet to `https://raw.githubusercontent.com/cosmology-tech/cosmos-kit/main/public/images/logos/wallets/wallet-name.ext`

**Comment by pyramation** [comment]
sounds great @vexxvakan :)
