### ISSUE TITLE
Integrate Fin Wallet Extension

### ISSUE THREAD

**Issue by khiemsoft** [cosmology-tech/cosmos-kit#223]
@pyramation  Please check my PR https://github.com/cosmology-tech/cosmos-kit/pull/222.
Here are some more info about Fin Wallet: https://twitter.com/fin_wallet
Thank you so much for your review.

**Comment by pyramation** [comment]
hey @khiemsoft does Sei use cosmjs and is it a typical Cosmos-based chain? Or is it that Sei wallet supports cosmos assets?

**Comment by khiemsoft** [comment]
@pyramation Yes, we are using CosmosJS with a Cosmos-based chain. Sei wallet supports Cosmos assets if you add a custom Cosmos network to Fin Wallet Extension. Ours is pretty much the same as Compass wallet from Leap
