### ISSUE TITLE
Handling of multiple chains

### ISSUE THREAD

**Issue by faboweb** [cosmology-tech/cosmos-kit#236]
If I run

```
const { address, connect } = useChain('cosmoshub')
const { address: osmoAddress } = useChain('osmosis')

...
connect()
```

and I use WalletConnect, the connection flip flops between Cosmos Hub and Osmosis in Keplr Mobile. Resulting in the client crashing.

How do I handle more then one network connection using your hooks?

**Comment by twhy** [comment]
@faboweb  Please try using the `useManager` hook and take a look at the example below to see if it fits your need for development.
https://github.com/cosmology-tech/cosmos-kit/blob/main/packages/example/pages/add-chain.tsx

**Comment by twhy** [comment]
Please use `useChains` hook in latest version of CosmosKit
