### ISSUE TITLE
Upgrade the dependencies to support the latest wasmd.

### ISSUE THREAD

**Issue by 99Kies** [cosmology-tech/cosmos-kit#259]
https://github.com/cosmology-tech/cosmos-kit/blob/main/packages/react/package.json#L87-L88

https://github.com/cosmos/cosmjs/issues/1452

**Comment by liujun93** [comment]
@99Kies Thanks. We've upgraded it in [CosmosKit V2](https://docs.cosmoskit.com/get-started#cosmoskit-v2) beta.
