### ISSUE TITLE
yarn install gives engine compatibility issues

### ISSUE THREAD

**Issue by shang-chi-7** [cosmology-tech/cosmos-kit#272]
I am trying to run the example project in packages but getting the node engine compatibility issue.
Step to reproduce:
1. Clone the cosmos kit repo
2. Try installing packages with yarn install.

yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning Pattern ["@walletconnect/types@^1.8.0"] is trying to unpack in the same destination "/Users/ajaysingh/Library/Caches/Yarn/v6/npm-@walletconnect-types-v1-1.8.0-3f5e85b2d6b149337f727ab8a71b8471d8d9a195-integrity/node_modules/@walletconnect/types-v1" as pattern ["@walletconnect/types-v1@npm:@walletconnect/types@1.8.0"]. This could result in non-deterministic behavior, skipping.
error nextra@2.8.0: The engine "node" is incompatible with this module. Expected version ">=16". Got "14.19.3"
error Found incompatible module.

<img width="874" alt="Screenshot 2023-07-24 at 3 58 38 PM" src="https://github.com/cosmology-tech/cosmos-kit/assets/106727518/57d35a9e-301e-4c3e-ad73-32f3da34c43e">

**Comment by liujun93** [comment]
not able to reproduce it
