### ISSUE TITLE
Vite dev server error `does not provide an export named`

### ISSUE THREAD

**Issue by janfabian** [cosmology-tech/cosmos-kit#281]
Hi, 
using latest vite.js and latest version (2.x.x) of the cosmos-kit library I'm getting following error, when I run `vite` command

```The requested module '/node_modules/.vite/deps/@cosmos-kit_react-lite.js?v=95f084f2' does not provide an export named 'ChainProvider'```

minimal reproduction workspace: https://stackblitz.com/edit/vitejs-vite-m4l45x

Would you by any chance know? Not sure if it is more cosmos-kit or vite related issue, but I'm trying my luck here. I noticed a note about `build process changed` in https://docs.cosmoskit.com/migration-to-v2, it might be related.

**Comment by pyramation** [comment]
We're on it! Thanks for reporting, we're aware and are looking into it. 

Which version of node are you running?

**Comment by liujun93** [comment]
@janfabian Can you upgrade to the latest? This shall be solved.

**Comment by janfabian** [comment]
@liujun93 @pyramation sorry for late response

awesome, I confirm it works like charm ! thanks
