### ISSUE TITLE
Type URL '/cosmos.authz.v1beta1.MsgExec' does not exist in the Amino message type register

### ISSUE THREAD

**Issue by JakeHartnell** [cosmology-tech/cosmos-kit#292]
Recently, after upgrading DAO DAO to use mainstream Cosmos kit, the Authz Exec actions on the [/me/tx page](https://daodao.zone/me/tx) have stopped working.

When trying to make an authz `MsgExec` action, the following error is returned:
```
Type URL '/cosmos.authz.v1beta1.MsgExec' does not exist in the Amino message type register.
If you need support for this message type, you can pass in additional entries to the AminoTypes constructor. 
```

Is it possible to pass in additional entries to the AminoTypes constructor somehow? We are using `useChain` from `@cosmos-kit/react-lite`. CC @NoahSaso for providing additional context if needed.

**Comment by NoahSaso** [comment]
I figured it out. We were loading types into the protobuf registry but not the amino converters registry, and switching to Cosmos Kit made us start using the amino type by default instead of direct. This is fixed now by also loading in all the Amino converters.
