### ISSUE TITLE
Add mobile Station Extension support

### ISSUE THREAD

**Issue by 0xFable** [cosmology-tech/cosmos-kit#299]
Cosmos-Kit now supports a bunch of good mobile options like Keplr or Comsosstation 

As a developer looking to use Cosmos-Kit
I want Mobile Station support powered by walletConnect
so that I can offer a full station experience to users on both mobile and web.

**Comment by sascha1337** [comment]
signed

Am Mo., 21. Aug. 2023 um 14:00 Uhr schrieb 0xFable ***@***.***

**Comment by liujun93** [comment]
Hi, @0xFable 

Usually the wallet integration is implemented by the the wallet developers or the one who need it. Can you help integrate station-mobile in if possible?  

https://docs.cosmoskit.com/integrating-wallets/adding-new-wallets#quickly-add-mobile-wallets

Or ask if the developer of `@cosmos-kit/station-extension` can help to integrate it? 

https://github.com/cosmology-tech/cosmos-kit/blob/a3638f3983c0ca3f72a776de2c53f8d90c548a25/wallets/station-extension/package.json#L5

**Comment by twhy** [comment]
@0xFable Can you confirm that Station Mobile App supports WalletConnect ?
It seems that Station Mobile doesn't support WalletConnect.
https://walletconnect.com/explorer?search=station
Station is not in the result list.
