### ISSUE TITLE
A react-modal warning for @cosmos-wallet/react@0.9.4

### ISSUE THREAD

**Issue by liujun93** [cosmology-tech/cosmos-kit#30]
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/44238025/184775899-772703be-4123-4a2f-ab2c-e71957fb62ca.png">

**Comment by pyramation** [comment]
does it still do this if you upgrade to 0.10.0?

**Comment by liujun93** [comment]
@pyramation yes. it's still there even upgraded to `@cosmos-kit/react@0.11.0`
