### ISSUE TITLE
metamask snap support

### ISSUE THREAD

**Issue by pyramation** [cosmology-tech/cosmos-kit#301]
- [x] #302
- [x] #303
- [x] #304
- [x] [Support "Avatar" component#479](https://github.com/cosmology-tech/projects-issues/issues/479)

**Comment by twhy** [comment]
<img width="312" alt="image" src="https://github.com/cosmology-tech/cosmos-kit/assets/7459812/e36b0559-cd45-48bf-9f4e-14e7eebcb451">
<img width="309" alt="image" src="https://github.com/cosmology-tech/cosmos-kit/assets/7459812/b33936e4-8a7d-4dba-8418-7bb69e2429f2">

<img width="315" alt="image" src="https://github.com/cosmology-tech/cosmos-kit/assets/7459812/6dfa7253-ac70-4f33-9e9c-920c419ded5d">
<img width="309" alt="image" src="https://github.com/cosmology-tech/cosmos-kit/assets/7459812/72558d5d-8779-4694-81ba-8a729f287728">

**Comment by twhy** [comment]
Flip the logos, according to the MetaMask team
<img width="313" alt="image" src="https://github.com/cosmology-tech/cosmos-kit/assets/7459812/932b8d6b-4423-4612-ac1a-ecb5ac46ca26">
