### ISSUE TITLE
icon to differentiate snaps from other wallets

### ISSUE THREAD

**Issue by pyramation** [cosmology-tech/cosmos-kit#303]
we'll have a product dilemma if snaps use metamask logo directly as we intend to directly support metamask, and using the metamask logo alone for snaps could create confusion. The keplr dashboard does a nice job of this with IBC assets as you can see in the image below

Similar to how keplr shows IBC assets, we should do this for snaps. This way we have consistency/cohesion for all the snaps as they are developed.

I think for light theme we use a small white circle, maybe dark theme is grey:

<img width="373" alt="Screen Shot 2023-08-23 at 4 02 33 PM" src="https://github.com/cosmology-tech/cosmos-kit/assets/545047/4c579fe0-b843-4d9b-bdc9-6cb1841a48b0">

**Comment by twhy** [comment]
<img width="300" alt="image" src="https://github.com/cosmology-tech/cosmos-kit/assets/7459812/e89a74bf-1e3b-4dbe-9a41-f3eea6d352a5">
<img width="298" alt="image" src="https://github.com/cosmology-tech/cosmos-kit/assets/7459812/0fbcb56e-9460-4535-99e8-dcb45b640ef5">
