### ISSUE TITLE
keplr-mobile walletconnect not working ios/safari

### ISSUE THREAD

**Issue by nick134-bit** [cosmology-tech/cosmos-kit#305]
Hey,
if i use the create-cosmos-app multichain template, launch it on my iphone and try to connect with keplr mobile it says: 
Safari cannot open the page because the address is invalid. 
This is also the case on app.osmosis.zone that afaik uses cosmos-kit.
Cosmostation and Leap are working.

**Comment by twhy** [comment]
@nick134-bit  It maybe a Keplr issue. Let me ask them.
