### ISSUE TITLE
Wallet gets disconnected when switching chains

### ISSUE THREAD

**Issue by vinodhum** [cosmology-tech/cosmos-kit#332]
Hi, 

When switching chains wallet gets disconnected, more info describing issue and steps to reproduce on the codebase .

As discussed on [discord](https://discord.com/channels/958479707123355748/1006709647509557329/1150964146817470474) here is code sample to reproduce the issue.

for some reason I could not create demo on stackblitz or codesandbox using nextJS and cosmosKit. So, here is the github repo you can clone https://github.com/fortytwomoney/cosmoskit-issue-demo.

Thank You

**Comment by MbBrainz** [comment]
What is the status of this issue?

**Comment by twhy** [comment]
@MbBrainz I'm working on it

**Comment by twhy** [comment]
@MbBrainz @vinodhum Please use `useChains` hook and take a look at the docs and the example.
Docs:  https://docs.cosmoskit.com/hooks/use-chains
Example: https://github.com/cosmology-tech/cosmos-kit/blob/main/packages/example/pages/use-chains.tsx

**Comment by vinodhum** [comment]
@twhy Thanx for update, will implement useChains and get back.

**Comment by vinodhum** [comment]
@twhy looks like adding chains dynamically is throwing error 
ex: adding migaloo to list of chains throws below error 
`Error: There is no chain info for migaloo-1`

```  
const supportedChains = [
    'cosmoshub',
    'osmosis',
    'migaloo',
  ]

 const chainFromQuery = query.fromChain as string

  const walletChains = useMemo(() => {
    if (!!chainFromQuery) {
       supportedChains.push(chainFromQuery)
    }
    return supportedChains
  }, [ chainFromQuery])

  const chains = useChains(walletChains)
