### ISSUE TITLE
@interchain-ui 'UserId' is not exported from 'react'

### ISSUE THREAD

**Issue by CaptainHoangLe** [cosmology-tech/cosmos-kit#338]
I am interacting cosmos-kit into my app using react version 17.0.2
![image](https://github.com/cosmology-tech/cosmos-kit/assets/53038465/972e76ec-d429-4cac-bb85-684c1cf9a98f)

I received an error

![image](https://github.com/cosmology-tech/cosmos-kit/assets/53038465/bc3a6daa-c844-4659-a2a9-c0f753b5efaf)

Can you give me a solution for this problem, please 
Thanks a lot

**Comment by twhy** [comment]
@CaptainHoangLe  Can you upgrade React to v18 ? It requres React 18+

**Comment by CaptainHoangLe** [comment]
> @CaptainHoangLe Can you upgrade React to v18 ? It requres React 18+
I actualy don't want to migrate to react v18 because some other package is stable on v17. I will find another solution if it possible. thank very much for your help. it is very useful

**Comment by yyyyaaa** [comment]
@CaptainHoangLe react 18 has been out since March 2022 so I think it's reasonable that we depend on it :)
