### ISSUE TITLE
No Chain Info for [chain-id] Error When Adding New Chains using useChains hook

### ISSUE THREAD

**Issue by twhy** [cosmology-tech/cosmos-kit#348]
From @vinodhum 
Adding chains dynamically is throwing error when use `useChains`
ex: adding migaloo to list of chains throws below error 
`Error: There is no chain info for migaloo-1`

```  
const supportedChains = [
    'cosmoshub',
    'osmosis',
    'migaloo',
  ]

 const chainFromQuery = query.fromChain as string

  const walletChains = useMemo(() => {
    if (!!chainFromQuery) {
       supportedChains.push(chainFromQuery)
    }
    return supportedChains
  }, [ chainFromQuery])

  const chains = useChains(walletChains)

**Comment by vinodhum** [comment]
When switching chain, wallet still changes to status disconnected or isWalletConnected is coming as false. Secondly, when click on connect gives attached error. 

```
"@cosmos-kit/core": "2.7.0",
"@cosmos-kit/keplr": "2.4.0",
"@cosmos-kit/react": "2.9.1"
```

<img width="984" alt="image" src="https://github.com/cosmology-tech/cosmos-kit/assets/5168174/71df163e-0d1d-45ef-ae76-d2d859e640d6">

**Comment by MbBrainz** [comment]
@twhy What is the status on this?
