### ISSUE TITLE
`<ChainProvider>` props cannot be changed after first render

### ISSUE THREAD

**Issue by Redm4x** [cosmology-tech/cosmos-kit#370]
It looks like the `<ChainProvider>` props cannot be changed after the first render. I am asynchronously loading the preferred rpc endpoint (from user settings) and then trying to set the `endpointOptions` prop, but it is not used during new transactions. It always uses what was set during the first render. I am guessing it is caused by the `useMemo` in [provider.tsx](https://github.com/cosmology-tech/cosmos-kit/blob/36cdcd4a6c4c6ccd8ecfa40b741e1b55465f2b49/packages/react-lite/src/provider.tsx#L56), but I could not find a workaround. Is there a way to update `endpointOptions` after the first render?

**Comment by baktun14** [comment]
Bump

**Comment by liujun93** [comment]
a new feature `addEndpoints` as been added in the latest version @cosmos-kit/react@2.9.14

you can follow the example code here https://github.com/cosmology-tech/cosmos-kit/blob/main/packages/example/pages/endpoint.tsx

**Comment by daniel-farina** [comment]
> a new feature `addEndpoints` as been added in the latest version @cosmos-kit/react@2.9.14
> 
> you can follow the example code here https://github.com/cosmology-tech/cosmos-kit/blob/main/packages/example/pages/endpoint.tsx

This is gold and one of the much needed features in Cosmos for decentralization and less dependency on centralized infrastructure.  Nice job guys.
