### ISSUE TITLE
Warning: Invalid DOM property `fill-rule`. Did you mean `fillRule`?

### ISSUE THREAD

**Issue by toshiSat** [cosmology-tech/cosmos-kit#371]
I am getting this error when calling `openView`.

It seems to be coming from the @interchain-ui package, but that package is not public.

I'm not using webpack, but using vite to compile my react app

**Comment by yyyyaaa** [comment]
@toshiSat hi, I'm fixing this in @interchain ui package, this can be safely ignored for now

**Comment by yyyyaaa** [comment]
fixed please update to the latest version @toshiSat
