### ISSUE TITLE
useChains() error at addChain() bad version

### ISSUE THREAD

**Issue by vexxvakan** [cosmology-tech/cosmos-kit#372]
Hey,

Getting this error whenever I try enabling a chain which is not yet added to Keplr over useChains().
I expected that Keplr pops up and asks to add the chain but it errored instead.

![image](https://github.com/cosmology-tech/cosmos-kit/assets/7051136/881ce392-a069-403f-9d56-a9c8b8d69e53)

**Comment by twhy** [comment]
@vexxvakan Can you provide a code sample that help reproduce the issue.
Also, the error `contact maintainers: bad version` comes from Keplr itself. 
In this case, it maybe the an issue of Keplr extension.

**Comment by vexxvakan** [comment]
Hey @twhy 

I created a repro example codesandbox [here](https://codesandbox.io/p/devbox/cosmos-kit-issue-qy3lvx)

just type in any chainName, not chain_id, and click "add chain". For already added chains it asks to approve the connection and for not yet added chains it throws the error mentioned above.

**Comment by vexxvakan** [comment]
It may be a problem that the chain-registry branch used in the package "chain-registry" is outdated and thus crashing? it is 3 months old now. @twhy

**Comment by twhy** [comment]
@vexxvakan  Thanks. Let me check it.

**Comment by MbBrainz** [comment]
@twhy any update on this?

**Comment by MbBrainz** [comment]
@twhy lmk if i can help you with anything

**Comment by twhy** [comment]
@MbBrainz You can read the source code of cosmos-kit to see if you can fix it. Or you can work on other parts of your app first. I will fix this ASAP.

**Comment by pyramation** [comment]
I think I have a fix for this one, stay tuned

**Comment by pyramation** [comment]
@MbBrainz can you try to upgrade `cosmos-kit` and/or `chain-registry`?

**Comment by MbBrainz** [comment]
I updated to the latest cosmos-kit and chain-registry version, and i have encountered a different error. When im connecting the wallet, it first shows the "cosmostation not installed" error and then i have to click `x` to go to the wallet connection screen. 

I made a small loom to show what is happening:
https://www.loom.com/share/dfdd19246d2b4cd0ba35fa53f761fc48?sid=6094e036-adba-4e81-88fc-5f13bd700dfb

The exact versions of cosmos-kit i have installed during this error are:
```json
{
    "@cosmjs/stargate": "^0.31.3",
    "@cosmos-kit/core": "2.7.10",
    "@cosmos-kit/cosmostation": "2.5.0",
    "@cosmos-kit/keplr": "2.5.0",
    "@cosmos-kit/keplr-extension": "^2.6.0",
    "@cosmos-kit/leap": "2.5.0",
    "@cosmos-kit/leap-extension": "^2.6.0",
    "@cosmos-kit/react": "2.9.14",
    "@cosmos-kit/terrastation": "^0.1.7",
    "@cosmos-kit/xdefi-extension": "2.5.12",
	...
    "chain-registry": "^1.23.0",
    }
```

**Comment by twhy** [comment]
@pyramation Please publish a new version of cosmos-kit which fixes the issue that @MbBrainz just found in the video.

**Comment by twhy** [comment]
@MbBrainz Does the original issue fixed after your upgrade ?

**Comment by vexxvakan** [comment]
@pyramation @twhy I just updated the Codesandbox with the newest versions and the initial issue is indeed gone!

We got the fix [here](https://github.com/cosmology-tech/chain-registry/pull/57)

Opened a new issue #380 for @MbBrainz' error because I have been seeing the same on another project of mine and now on this one as well

**Comment by pyramation** [comment]
if anyone has this re-appear — please use npm/yarn resolutions prop in your package to pin to the fixed version — currently that is 

```
@cosmos-kit/keplr@2.5.0
@chain-registry/keplr@1.29.0
```
