### ISSUE TITLE
can not seem to switch chains

### ISSUE THREAD

**Issue by PFC-developer** [cosmology-tech/cosmos-kit#78]
hi.
I'm trying to build a dApp that uses multiple chains at once.

I'm doing
```
  walletManager.setCurrentChain('osmosis');
  await walletManager.connect();
```
which seems to switch the chain, and get the correct address.
*but*
```
  const res = await walletManager.signAndBroadcast(voteMessages);
```
fails with
```
 Query failed with (18): fee payer address:  does not exist: unknown address: invalid request
```
the same code appears to work fine when only 1 setCurrentChain has been executed. (it's like the second call doesn't setup something correctly

**Comment by pyramation** [comment]
thanks @PFC-developer we'll take a look at this asap!

cc @liujun93

**Comment by liujun93** [comment]
use `ChainProvider` and `useChain` instead. 

https://docs.cosmoskit.com/provider/chain-provider

https://docs.cosmoskit.com/hooks/use-chain
