### ISSUE TITLE
arbitrary signatures

### ISSUE THREAD

**Issue by pyramation** [cosmology-tech/cosmos-kit#89]
https://github.com/cosmos/cosmos-sdk/blob/main/docs/architecture/adr-036-arbitrary-signature.md

**Comment by findolor** [comment]
There is a repo for showing off how to work with arbitrary signatures to implement login in a server. 

It also has the frontend side that shows how to do the signing properly: https://github.com/wgwz/simple-express-keplr-passport/blob/abb72f632737256f75d4be9c7fde5a0db20a069d/frontend/src/App.tsx#L96

Can be used as a reference for implementing the arbitrary signing 👍

**Comment by pyramation** [comment]
hey @liujun93 do we expose the `signArbitrary` method?
