### ISSUE TITLE
react dependencies that shouldn't be in certain packages

### ISSUE THREAD

**Issue by pyramation** [cosmology-tech/cosmos-kit#92]
I'm noticing `@chakra-ui/react` and other react deps in core packages like leap, trust, etc. Are these actually used?

**Comment by sascha1337** [comment]
The more stripped and barebone, the better.
Some want to use tailwind, some aim to use react95 For UI 😊 - also, some
prefer preact // vue3 // svelte - would be great to have some kit, that
works agnostic of the framework, i guess 💡 solid point

**Comment by liujun93** [comment]
> I'm noticing `@chakra-ui/react` and other react deps in core packages like leap, trust, etc. Are these actually used?

removed in the latest version. thanks.
